### ISSUE TITLE
Task with name 'compileJava' not found in root project

### ISSUE THREAD

**Issue by rgozim** [zeroc-ice/ice-builder-gradle#7]
Using the new gradle plugin syntax to include the zeroc slice plugin results in an error.

Example:
```
plugins {
    id "java"
    id "com.zeroc.gradle.ice-builder.slice" version "1.4.5"
}
```

Stacktrace:
```
Caused by: org.gradle.api.UnknownTaskException: Task with name 'compileJava' not found in root project 'omero-blitz'.
	at org.gradle.api.internal.tasks.DefaultTaskCollection.createNotFoundException(DefaultTaskCollection.java:97)
	at org.gradle.api.internal.tasks.DefaultTaskCollection.createNotFoundException(DefaultTaskCollection.java:44)
	at org.gradle.api.internal.DefaultNamedDomainObjectCollection.getByName(DefaultNamedDomainObjectCollection.java:329)
	at org.gradle.api.internal.tasks.DefaultTaskCollection.getByName(DefaultTaskCollection.java:44)
	at org.gradle.api.tasks.TaskCollection$getByName.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at com.zeroc.gradle.icebuilder.slice.SlicePlugin.apply(SlicePlugin.groovy:42)
	at com.zeroc.gradle.icebuilder.slice.SlicePlugin.apply(SlicePlugin.groovy)
	at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:42)
```

[This code ](https://github.com/zeroc-ice/ice-builder-gradle/blob/90506a510b12f1744b2cd5af86380925c4f14b59/src/main/groovy/com/zeroc/gradle/icebuilder/slice/SlicePlugin.groovy#L42)should probably be contained within a `project.afterEvalute` block.

**Comment by pepone** [comment]
Hi @rgozim we have published 1.4.6 with a fix for this issue

Bests regards,
José
